- name: "Ls the root"
  become: true
  command: ls /root/project/backend

- name: "Ls home ubuntu"
  become: true
  command: ls /home/ubuntu

- name: "Get project/backend files from circleci server to local"
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "cd to backend dir"
  become: true
  command: cd /home/ubuntu/backend    

- name: "run npm install"
  become: true
  command: npm install
    
- name: "run npm run build"
  become: true
  command: npm run build

- name: "PM2 to run back-end server"
  become: true
  command: pm2 start npm -- run "start"