- name: Upgrade all apt packages
  apt:
    name: "*"
    state: latest

- name: "Get project/backend files from circleci server to local"
  become: true
  copy:
    src: ~/project/backend/
    dest: /home/ubuntu/backend/

- name: "CD to dir"
  become: true
  command: ls
  args: 
    chdir: /home/ubuntu/backend

- name: "LS backend"
  become: true
  command: ls

- name: "NPM install"
  become: true
  command: npm install

- name: "NPM Run Build"
  become: true
  command: npm run build

- name: "LS to verify the dist"
  become: true
  command: ls

# - name: "Get project/backend files from circleci server to local"
#   become: true
#   copy:
#     src: ~/project/backend/dist
#     dest: /home/ubuntu/backend/

- name: "cd to backend dir"
  become: true
  command: cd /home/ubuntu/backend    

# - name: "run npm install"
#   become: true
#   command: npm install
    
# - name: "run npm run build"
#   become: true
#   command: npm run build

- name: "PM2 to run back-end server"
  become: true
  command: pm2 start npm -- run "start"