- name: "change directories to backend"
  become: true
  command: cd backend

- name: "NPM Install"
  become: true
  command: npm install

- name: "NPM Run Build"
  become: true
  command: npm run build

- name: "Get project/backend files from circleci server to local"
  become: true
  copy:
    src: ./dist
    dest: /home/ubuntu/backend

# - name: "cd to backend dir"
#   become: true
#   command: cd /home/ubuntu/backend    

# - name: "run npm install"
#   become: true
#   command: npm install
    
# - name: "run npm run build"
#   become: true
#   command: npm run build

- name: "PM2 to run back-end server"
  become: true
  command: pm2 start npm -- run "start"