# - name: "Get project/backend files from circleci server to local"
#   become: true
#   ansible.builtin.copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: "cd to backend dir"
  command: cd /home/ubuntu/backend    

- name: "run npm install"
  command: npm install
    
- name: "run npm run build"
  command: npm run build

- name: "PM2 to run back-end server"
  command: pm2 start npm -- run "start"